version: "3"
services:
  dis-web:
    restart: always
    build: .
    container_name: "dis-web"
    ports:
      - 7860:7860
    tty: true
    command: python app.py
    volumes:
      - ./:/src_container
